pipeline:
  test-step:
    image: python:${PY_VERSION}-${PY_TAG}
    commands:
      - pip install --editable .
      - python -m unittest discover -v -s tests -p test_*.py
matrix:
  PY_VERSION:
    - 3.10
  PY_TAG:
    - slim
    - bullseye